version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/sparkle-functions/functions
    steps:
      - checkout
      - run:
          name: Where am I?
          command: pwd
      - run:
          name: What's in here?
          command: ls
      - run:
          name: Install Dependencies
          command: yarn

  test:
    docker:
      - image: circleci/node:6.11
    working_directory: ~/sparkle-functions/functions
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: yarn test-unit
      - run:
          name: End to End Tests
          command: yarn test-e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
