version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
      - run:
          name: Install Dependencies
          command: yarn
          working_directory: functions
      - save_cache:
          key: dependency-cache-{{ checksum "functions/package.json" }}
          paths:
            - ./functions/node_modules
      - run:
          name: Unit Tests
          command: yarn test-unit
          working_directory: functions
      - run:
          name: End to End Tests
          command: yarn test-e2e
          working_directory: functions

  deploy-staging:
    docker:
      - image: mj3000/firebase-tools
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
          working_directory: functions
      - run:
          command: NODE_ENV=production ./scripts/deploy-functions.sh staging

  deploy-production:
    docker:
      - image: mj3000/firebase-tools
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
          working_directory: functions
      - run:
          command: NODE_ENV=production ./scripts/deploy-functions.sh production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: production
