name: Deploy

on:
  push:
    branches:
      - production
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: mj3000/firebase-tools

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install
        working-directory: ./functions

      - name: Use staging project
        if: github.ref == 'refs/heads/staging'
        run: firebase use ${{ secrets.STAGING_FIREBASE_PROJECT }} --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Use production project
        if: github.ref == 'refs/heads/production'
        run: firebase use ${{ secrets.PRODUCTION_FIREBASE_PROJECT }} --non-interactive --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy staging functions
        if: github.ref == 'refs/heads/staging'
        env:
          NODE_ENV: production
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_DB_URL: ${{ secrets.STAGING_FIREBASE_DB_URL }}
          FIREBASE_FUNCTIONS_AUTH: ${{ secrets.STAGING_FIREBASE_FUNCTIONS_AUTH }}
          SLACK_CLIENT_SECRET: ${{ secrets.STAGING_SLACK_CLIENT_SECRET }}
          GOOGLE_CLOUD_PROJECT: sapphire-inspections
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          FIREBASE_TEST_DB_URL: ${{ secrets.STAGING_FIREBASE_TEST_DB_URL }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.STAGING_FIREBASE_STORAGE_BUCKET }}
          COBALT_DOMAIN: ${{ secrets.STAGING_COBALT_DOMAIN }}
          CLIENT_DOMAIN: https://staging.sapphire-standard.com
          GLOBAL_API_TOKEN: ${{ secrets.STAGING_GLOBAL_API_TOKEN }}
        run: ./scripts/deploy-functions.sh production

      - name: Deploy production functions
        if: github.ref == 'refs/heads/production'
        env:
          NODE_ENV: production
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_DB_URL: ${{ secrets.PRODUCTION_FIREBASE_DB_URL }}
          FIREBASE_FUNCTIONS_AUTH: ${{ secrets.PRODUCTION_FIREBASE_FUNCTIONS_AUTH }}
          SLACK_CLIENT_SECRET: ${{ secrets.PRODUCTION_SLACK_CLIENT_SECRET }}
          GOOGLE_CLOUD_PROJECT: sapphire-inspections
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          FIREBASE_TEST_DB_URL: ${{ secrets.PRODUCTION_FIREBASE_TEST_DB_URL }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.PRODUCTION_FIREBASE_STORAGE_BUCKET }}
          COBALT_DOMAIN: ${{ secrets.PRODUCTION_COBALT_DOMAIN }}
          CLIENT_DOMAIN: https://bluestone-prop.sapphire-standard.com
          GLOBAL_API_TOKEN: ${{ secrets.PRODUCTION_GLOBAL_API_TOKEN }}
        run: ./scripts/deploy-functions.sh production
