name: Test

on:
  push:
    branches-ignore:
      - production
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:10.15-alpine

    steps:
      - uses: actions/checkout@v1

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: functions/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('functions/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install dependencies
        run: yarn install
        working-directory: ./functions

      # - name: Run unit tests
      #   run: yarn test-unit
      #   working-directory: ./functions
      #   env:
      #     FIREBASE_FUNCTIONS_AUTH: ${{ secrets.PRODUCTION_FIREBASE_FUNCTIONS_AUTH }}
      #     SLACK_CLIENT_SECRET: ${{ secrets.PRODUCTION_SLACK_CLIENT_SECRET }}

      - name: Fail Test
        continue-on-error: true
        run: NODE_ENV=test LOG_LEVEL=crit ./node_modules/.bin/mocha ./test/end-to-end/cleanup-inspection-proxy-orphans-sync.test.js
        working-directory: ./functions
        env:
          FIREBASE_FUNCTIONS_AUTH: ${{ secrets.PRODUCTION_FIREBASE_FUNCTIONS_AUTH }}
          SLACK_CLIENT_SECRET: ${{ secrets.PRODUCTION_SLACK_CLIENT_SECRET }}
          GOOGLE_CLOUD_PROJECT: sapphire-inspections
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

      - name: Run End to End Tests
        run: yarn test-e2e
        working-directory: ./functions
        env:
          FIREBASE_FUNCTIONS_AUTH: ${{ secrets.PRODUCTION_FIREBASE_FUNCTIONS_AUTH }}
          SLACK_CLIENT_SECRET: ${{ secrets.PRODUCTION_SLACK_CLIENT_SECRET }}
          GOOGLE_CLOUD_PROJECT: sapphire-inspections
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
